name: Test that the project is runnable with new action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job
    steps:
    - name: Step
      uses: opensafely/research-action@main
